# generated by ChatGPT 4o, optimal prompts。 在验证集上多次生成。
disease_descriptors_chexpert = {
    'No Finding': [
        'clear lung fields without focal opacities',
        'normal cardiac and mediastinal contours',
        'sharp costophrenic and cardiophrenic angles',
        'no pleural effusion or pneumothorax',
        'no evidence of pulmonary edema or consolidation',
        'no displaced fractures or osseous abnormalities',
        'no support devices or foreign bodies present'
    ],
    'Enlarged Cardiomediastinum': [
        'widening of the mediastinal silhouette',
        'increased cardiothoracic ratio',
        'obliteration of the retrosternal clear space on lateral view',
        'convexity of the left heart border',
        'abnormal contour of the right paratracheal stripe',
        'superior mediastinal widening',
        'double density sign on the right heart border'
    ],
    'Cardiomegaly': [
        'increased cardiothoracic ratio greater than 0.5 on PA view',
        'enlargement of the cardiac silhouette',
        'bulging of the left heart border',
        'rounding of the cardiac apex',
        'loss of the normal waist of the left heart border',
        'displacement of the left hemidiaphragm inferiorly',
        'double density sign on right heart border'
    ],
    'Lung Opacity': [
        'focal or diffuse increased pulmonary parenchymal density',
        'ill-defined or confluent airspace opacities',
        'air bronchograms within regions of consolidation',
        'loss of normal vascular markings in the affected region',
        'silhouetting of adjacent cardiac or diaphragmatic borders',
        'reticular or ground-glass pattern in the lungs',
        'segmental or lobar distribution of opacification'
    ], 
    'Lung Lesion': [
        'solitary pulmonary nodule or mass',
        'irregular or spiculated margins of the lesion',
        'cavitation within a focal opacity',
        'calcification within a pulmonary nodule',
        'lobulated or well-circumscribed mass in lung parenchyma',
        'air-fluid level within the lesion',
        'displacement of adjacent lung structures by mass effect'
    ],
    'Edema': [
        'bilateral perihilar airspace opacities in a batwing distribution',
        'cephalization of pulmonary vessels',
        'Kerley B lines in the lower lung zones',
        'increased interstitial markings',
        'fluid in the interlobar fissures',
        'enlarged cardiac silhouette suggesting hydrostatic cause',
        'pleural effusions particularly in dependent angles'
    ], 
    'Consolidation': [
        'homogeneous increase in pulmonary parenchymal opacity',
        'air bronchograms within the area of opacity',
        'segmental or lobar distribution of opacification',
        'silhouetting of adjacent cardiac or diaphragmatic borders',
        'preservation of lung volume in the affected area',
        'no evidence of volume loss or mass effect'
    ], 
    'Pneumonia': [
        'focal or lobar airspace opacity',
        'air bronchograms within the area of consolidation',
        'ill-defined margins of opacification',
        'silhouetting of adjacent cardiac or diaphragmatic borders',
        'segmental or lobar distribution of consolidation',
        'increased parenchymal density with preserved lung volume',
        'absence of cavitation or mass effect'
    ], 
    'Atelectasis': [
        'displacement of interlobar fissures',
        'crowding of pulmonary vessels',
        'elevation of the hemidiaphragm',
        'mediastinal shift toward the affected side',
        'compensatory hyperinflation of adjacent lung',
        'increased opacity in affected region',
        'loss of volume in the affected lobe or lung',
        'displacement of hilum toward the affected side',
        'narrowing of the rib spaces on affected side',
        'silhouetting of adjacent cardiac or diaphragmatic borders'
    ], 
    'Pneumothorax': [
        'visceral pleural line with absent lung markings beyond it',
        'increased lucency of the affected hemithorax',
        'deep sulcus sign on supine films',
        'collapse of the adjacent lung parenchyma',
        'shift of mediastinal structures in tension pneumothorax',
        'sharp delineation of cardiac or diaphragmatic borders',
        'absence of vascular markings peripheral to the pleural line'
    ], 
    'Pleural Effusion': [
        'blunting of the costophrenic angle',
        'meniscus sign with upward concave fluid level',
        'homogeneous opacity in the lower lung zone',
        'mediastinal shift away from the effusion in large volumes',
        'layering fluid in lateral decubitus view',
        'obscuration of the hemidiaphragm or cardiac border',
        'increased density in the affected hemithorax'
    ], 
    'Pleural Other': [
        'focal or diffuse pleural thickening',
        'calcified pleural plaques',
        'irregular or nodular pleural contour',
        'extrapleural sign with smooth convex opacity',
        'pleural-based mass with obtuse angles to the chest wall',
        'localized pleural opacity without layering',
        'pleural calcifications along the diaphragmatic or lateral margins'
    ],
    'Fracture': [
        'discontinuity of the cortical bone',
        'lucent fracture line across the rib or clavicle',
        'step-off deformity or misalignment of bone fragments',
        'bone fragment displacement or overriding',
        'callus formation in healing fractures',
        'periosteal reaction or sclerosis in subacute phase',
        'associated soft tissue swelling adjacent to the fracture site'
    ], 
    'Support Devices': [
        'endotracheal tubes or airway devices',
        'central venous catheters or vascular lines',
        'pacemakers or cardiac implantable devices',
        'chest tubes or drainage catheters',
        'gastric or feeding tubes',
        'surgical clips or sternal wires',
        'mammoplasty implants or prosthetic materials'
    ]
}
# Auto‑generated descriptor list (short label + brief description)

disease_descriptors_chestxray14 = {
    'Atelectasis': [
        'displacement of interlobar fissures',
        'crowding of pulmonary vessels',
        'elevation of the hemidiaphragm',
        'mediastinal shift toward the affected side',
        'compensatory hyperinflation of adjacent lung',
        'increased opacity in affected region',
        'loss of volume in the affected lobe or lung',
        'displacement of hilum toward the affected side',
        'narrowing of the rib spaces on affected side',
        'silhouetting of adjacent cardiac or diaphragmatic borders'
    ], 
    'Cardiomegaly': [
        'increased cardiothoracic ratio greater than 0.5 on PA view',
        'enlargement of the cardiac silhouette',
        'bulging of the left heart border',
        'rounding of the cardiac apex',
        'loss of the normal waist of the left heart border',
        'displacement of the left hemidiaphragm inferiorly',
        'double density sign on right heart border'
    ],
    'Edema': [
        'bilateral perihilar airspace opacities in a batwing distribution',
        'cephalization of pulmonary vessels',
        'Kerley B lines in the lower lung zones',
        'increased interstitial markings',
        'fluid in the interlobar fissures',
        'enlarged cardiac silhouette suggesting hydrostatic cause',
        'pleural effusions particularly in dependent angles'
    ], 
    'Consolidation': [
        'homogeneous increase in pulmonary parenchymal opacity',
        'air bronchograms within the area of opacity',
        'segmental or lobar distribution of opacification',
        'silhouetting of adjacent cardiac or diaphragmatic borders',
        'preservation of lung volume in the affected area',
        'no evidence of volume loss or mass effect'
    ], 
    'Pneumonia': [
        'focal or lobar airspace opacity',
        'air bronchograms within the area of consolidation',
        'ill-defined margins of opacification',
        'silhouetting of adjacent cardiac or diaphragmatic borders',
        'segmental or lobar distribution of consolidation',
        'increased parenchymal density with preserved lung volume',
        'absence of cavitation or mass effect'
    ], 

    'Pneumothorax': [
        'visceral pleural line with absent lung markings beyond it',
        'increased lucency of the affected hemithorax',
        'deep sulcus sign on supine films',
        'collapse of the adjacent lung parenchyma',
        'shift of mediastinal structures in tension pneumothorax',
        'sharp delineation of cardiac or diaphragmatic borders',
        'absence of vascular markings peripheral to the pleural line'
    ], 
    'Pleural Effusion': [
        'blunting of the costophrenic angle',
        'meniscus sign with upward concave fluid level',
        'homogeneous opacity in the lower lung zone',
        'mediastinal shift away from the effusion in large volumes',
        'layering fluid in lateral decubitus view',
        'obscuration of the hemidiaphragm or cardiac border',
        'increased density in the affected hemithorax'
    ], 
    'Infiltration': [
        'patchy opacities in the lung field',
        'ill-defined alveolar densities',
        'hazy pulmonary opacities',
        'non-segmental airspace opacification',
        'reticulonodular shadowing',
        'localized increase in pulmonary density',
        'subtle consolidation without air bronchogram',
        'asymmetric lung opacities'
    ],
    'Mass': [
        'well-circumscribed pulmonary opacity',
        'solitary round lesion larger than 3 cm',
        'lobulated soft-tissue density in lung field',
        'sharp marginated lesion not crossing fissures',
        'peripheral or central lung opacity with homogeneous density',
        'non-calcified opacity with spiculated borders',
        'air bronchogram absent within the lesion',
        'displacement of adjacent structures by mass effect'
    ],
    'Nodule': [
        'well-defined round opacity in lung field',
        'solitary pulmonary lesion less than 3 cm',
        'non-calcified circumscribed nodule',
        'sharp marginated lesion without associated consolidation',
        'peripheral round density separate from hilum',
        'absence of air bronchogram within the lesion',
        'unchanged location across serial imaging',
        'no associated pleural reaction'
    ],
    'Emphysema': [
        'hyperlucent lung fields',
        'flattened diaphragms',
        'increased retrosternal airspace',
        'vertical orientation of the heart',
        'barrel-shaped chest',
        'decreased vascular markings in peripheral lung zones',
        'enlarged intercostal spaces',
        'bullae formation in lung parenchyma'
    ],
    'Fibrosis': [
        'reticular opacities in the lung bases',
        'volume loss in affected lung regions',
        'traction bronchiectasis',
        'irregular linear densities',
        'honeycombing pattern in subpleural zones',
        'elevated hila due to fibrotic contraction',
        'blunting of costophrenic angles with fibrotic bands',
        'displacement of interlobar fissures'
    ],
    'Pleural Thickening': [
        'irregular pleural margins',
        'localized linear opacity along the pleural surface',
        'obliteration of costophrenic angle',
        'blunting of lateral thoracic wall contour',
        'apical pleural capping',
        'thickened pleural lines extending along the chest wall',
        'associated volume loss in underlying lung',
        'sharp demarcation between thickened pleura and aerated lung'
    ],
    'Hernia': [
        'air-fluid level in retrocardiac area',
        'rounded lucency with soft tissue rim in lower thorax',
        'bowel gas pattern within thoracic cavity',
        'elevated hemidiaphragm with gastric bubble above',
        'disruption of diaphragmatic contour',
        'mediastinal shift due to herniated abdominal contents',
        'opacified lower lung zone with internal lucencies',
        'blurring of diaphragmatic outline'
    ]
}