# generated by ChatGPT o3, optimal prompts。 在测试集上多次生成，不是很科学，但迁移结果还算稳定。
disease_descriptors_chexpert = {
    'No Finding': [
        'symmetrical aerated lungs without focal opacity or interstitial pattern',                       # :contentReference[oaicite:9]{index=9}
        'cardiothoracic ratio ≤ 0.50 with non-bulging heart borders',                                     # :contentReference[oaicite:10]{index=10}
        'sharp bilateral costophrenic and cardiophrenic angles without blunting',                        # :contentReference[oaicite:11]{index=11}
        'continuous pulmonary vascular markings to chest wall with no visceral pleural line',            # :contentReference[oaicite:12]{index=12}
        'midline trachea and right paratracheal stripe ≤ 4 mm',                                          # :contentReference[oaicite:13]{index=13}
        'smooth hemidiaphragms at normal inspiratory position',                                          # :contentReference[oaicite:14]{index=14}
        'intact bony thorax without cortical discontinuity',                                             # :contentReference[oaicite:15]{index=15}
        'no intrathoracic tubes, catheters, or metallic implants'                                        # :contentReference[oaicite:16]{index=16}
    ],
    'Enlarged Cardiomediastinum': [
        'cardiothoracic ratio > 0.50 on erect PA radiograph',                                # :contentReference[oaicite:0]{index=0}
        'globular / symmetric “water-bottle” cardiac silhouette',                           # :contentReference[oaicite:1]{index=1}
        'general widening of mediastinal contours (broad right paratracheal–aortic margin)',# :contentReference[oaicite:2]{index=2}
        'convex bulging of the left heart border (prominent third mogul) from left-atrial enlargement',   # :contentReference[oaicite:3]{index=3}
        'lateral and posterior displacement of cardiac border on PA & lateral views from ventricular enlargement' # :contentReference[oaicite:4]{index=4}
    ], 
    'Cardiomegaly': [
        'cardiothoracic ratio > 0.5 on erect PA view',
        'transverse cardiac width increase > 1 cm versus prior study',
        'globular (“water-bottle”) cardiac silhouette',
        'convex left atrial appendage forming third mogul',
        'apex displaced laterally & inferiorly (left-ventricular bulge)',
        'right heart border projects markedly right of spine',
        'retrosternal clear space obliterated on lateral view',
        'cardiac silhouette contacts > 50 % of lower sternum on lateral view'
    ],
    'Lung Opacity': [
        'focal or diffuse parenchymal area of increased density compared with adjacent aerated lung',                     # :contentReference[oaicite:0]{index=0}
        'homogeneous airspace consolidation that obscures vessel and airway margins',                                     # :contentReference[oaicite:1]{index=1}
        'hazy ground-glass opacity with preservation of bronchovascular outlines',                                         # :contentReference[oaicite:2]{index=2}
        'air bronchogram pattern of air-filled bronchi coursing through opaque lung',                                      # :contentReference[oaicite:3]{index=3}
        'silhouette sign with loss of normal heart, diaphragm, or vessel border adjacent to opacity',                      # :contentReference[oaicite:4]{index=4}
        'reticular or reticulonodular network of linear / micronodular opacities in interstitial disease'                  # :contentReference[oaicite:5]{index=5}
    ], 
    'Lung Lesion': [
        'solitary rounded opacity ≤ 3 cm (pulmonary nodule)',
        'focal soft-tissue opacity > 3 cm (pulmonary mass)',
        'lucent cavity within nodule or mass (cavitating lesion)',
        'air–fluid level inside cavitary lesion',
        'multiple discrete rounded opacities 2–10 mm (nodular pattern)',
        'innumerable tiny (< 3 mm) nodules diffusely distributed (miliary pattern)'
    ],
    'Edema': [
        'cephalization of pulmonary vessels',
        'smooth interlobular septal thickening (Kerley B lines)',
        'peribronchial cuffing with indistinct vascular margins',
        'bilateral perihilar alveolar opacities (bat-wing pattern)',
        'fluffy airspace consolidation in mid–lower lung zones',
        'bilateral pleural effusions',
        'fluid-thickened pulmonary fissures'
    ], 
    'Consolidation': [
        'homogeneous airspace opacity replacing aerated lung',                                  # :contentReference[oaicite:0]{index=0}
        'opacity obscuring pulmonary vessel and airway margins',                                # :contentReference[oaicite:1]{index=1}
        'air bronchogram sign of air-filled bronchi within consolidated lung',                  # :contentReference[oaicite:2]{index=2}
        'silhouette sign with loss of heart, diaphragm, or vessel border adjacent to opacity',  # :contentReference[oaicite:3]{index=3}
        'lobar or segmental homogeneous opacity bounded by fissures'                           # :contentReference[oaicite:4]{index=4}
    ]
, 
    'Pneumonia': [
        'lobar homogeneous airspace consolidation',                                # :contentReference[oaicite:0]{index=0}
        'air bronchogram sign within opacity',                                     # 
        'silhouette sign with loss of heart, aortic, or diaphragm border',         # 
        'segmental or fissure-bounded triangular opacity',                         # :contentReference[oaicite:1]{index=1}
        'multifocal patchy alveolar opacities',                                    # 
        'cavitary consolidation with air–fluid level',                             # :contentReference[oaicite:2]{index=2}
        'ground-glass opacity in affected lung zones'                              # :contentReference[oaicite:3]{index=3}
    ], 
    'Atelectasis': [
        'increased lung opacity with volume loss',
        'interlobar fissure shift toward opacity',
        'mediastinal or tracheal shift toward affected side',
        'elevated ipsilateral hemidiaphragm',
        'crowded pulmonary vessels and bronchi',
        'ipsilateral hilar displacement',
        'juxtaphrenic peak sign',
        'compensatory hyperinflation of adjacent lobe'
    ], 
    'Pneumothorax': [
        'visceral pleural line with absent peripheral lung markings',
        'peripheral hyperlucent pleural space',
        'collapsed lung retracted toward hilum',
        'deep costophrenic sulcus sign on supine film',
        'mediastinal shift away from affected side (tension)',
        'flattened or depressed ipsilateral hemidiaphragm (tension)',
        'subcutaneous emphysema outlining chest wall soft tissues'
    ], 
    'Pleural Effusion': [
        'blunting of lateral costophrenic angle',
        'blunting of posterior costophrenic angle',
        'pleural meniscus sign',
        'fluid tracking up lateral pleural space',
        'layered pleural fluid posteriorly on supine view',
        'apparent elevation of hemidiaphragm (subpulmonic effusion)',
        'stomach bubble sign',
        'mediastinal shift away from opaque hemithorax',
        'lenticular opacity within fissure (pseudotumor)',
        'loculated pleural fluid with convex margin and obtuse costal angle'
    ], 
    'Pleural Other': [
        'well-demarcated calcified pleural plaque',
        'bilateral diaphragmatic pleural calcification',
        'diffuse nodular pleural thickening encasing lung',
        'pleural-based soft-tissue mass with obtuse chest-wall angle',
        'apical cap of pleural fibrosis at lung apex',
        'peripheral rounded atelectasis with comet-tail vessels',
        'linear parenchymal band extending to thickened pleura',
        'subpleural curvilinear line within 1 cm of pleura'
    ],
    'Fracture': [
        'lucent cortical discontinuity of a rib or other thoracic bone',                            # :contentReference[oaicite:0]{index=0}
        'sharp linear fracture line traversing the bone cortex',                                    # :contentReference[oaicite:1]{index=1}
        'step-off or angulation of bone ends indicating displacement',                              # :contentReference[oaicite:2]{index=2}
        'irregular cortical thickening or callus consistent with healed fracture',                  # :contentReference[oaicite:3]{index=3}
        'adjacent subcutaneous emphysema overlying the fracture site',                              # :contentReference[oaicite:4]{index=4}
        'localized soft-tissue swelling or hematoma contiguous with the break'                      # :contentReference[oaicite:5]{index=5}
    ], 
    'Support Devices': [
        "Endotracheal tubes",
        "Central venous catheters",
        "Nasogastric or orogastric tubes",
        "Pacemakers or cardiac devices",
        "Biventricular pacing leads",
        "Chest tubes",
        "Mechanical heart valves",
        
        "Surgical sponges with radiopaque markers",
        "Postoperative drainage tubes",
        "Aspirated metallic pins",
        "Ingested chicken bone fragments",
        "Bullets or shrapnel",
        "Body piercings or nipple rings",
    ]

}
# Auto‑generated descriptor list (short label + brief description)

disease_descriptors_chestxray14 = {
    "Cardiomegaly": [
        "Cardiothoracic Ratio > 0.5 — Maximal transverse cardiac diameter exceeds 50% of thoracic width",
        "Left Ventricular Lateral Bulge — Outward bowing of left cardiac border and apex",
        "Left Atrial Convexity — Additional upper‑left contour created by enlarged left atrium",
        "Right Atrial Border Prominence — Right heart edge projects unusually far right of spine",
        "Right Ventricular Sternal Contact — Cardiac silhouette abuts >50% of lower sternum on lateral view",
        "Globular Silhouette — Symmetric, rounded ‘water‑bottle’ heart outline",
    ],
    "Edema": [
        "Cephalization of Pulmonary Vessels — Upper‑lobe veins equal or exceed size of lower‑lobe veins",
        "Indistinct Vascular Margins — Blurred vessel borders due to interstitial fluid",
        "Kerley B Lines — Short horizontal septal lines at lung bases",
        "Kerley A Lines — 2–6 cm oblique septal lines radiating toward hila",
        "Peribronchovascular Cuffing — Hazy linear opacities around bronchi and vessels",
        "Alveolar Edema Opacities — Fluffy perihilar air‑space densities obscuring vessels",
        "Bilateral Pleural Effusions — Costophrenic angle blunting from transudate",
    ],
    "Consolidation": [
        "Homogeneous Air-Space Opacity — Water‑density replacement of alveolar air",
        "Vascular & Airway Margin Obliteration — Loss of sharp internal lung markings",
        "Air Bronchogram Sign — Dark branching air‑filled bronchi within dense lung",
        "Silhouette Sign — Disappearance of heart or diaphragm border where opacity abuts",
        "Fissure-Bound Lobar Contour — Sharp straight/curved edge along interlobar fissure",
        "Patchy Air-Space Densities — Scattered fluffy opacities in multifocal disease",
    ],
    "Pneumonia": [
        "Alveolar Consolidation — New homogeneous air‑space density typical of infection",
        "Air Bronchogram Sign — Patent bronchi outlined by surrounding opacity",
        "Silhouette Sign Loss — Obscuration of normal soft‑tissue interfaces",
        "Fissure-Bound Lobar Opacity — Dense shadow limited by fissures",
        "Patchy Air-Space Shadows — Irregular multifocal opacities of bronchopneumonia",
        "Intracavitary Air-Fluid Level — Horizontal interface within a cavitating focus",
        "Thin-Walled Pneumatocele — Transient thin‑walled gas cavity",
    ],
    "Atelectasis": [
        "Fissure Displacement — Interlobar fissure moves toward collapsed lobe",
        "Crowded Vessels/Bronchi — Pulmonary structures lie unusually close together",
        "Increased Parenchymal Opacity — Dense appearance of airless lung segment",
        "Mediastinal Shift Toward Collapse — Trachea/heart deviate ipsilaterally",
        "Hilar Displacement — Hilum elevates with upper‑lobe loss, lowers with lower‑lobe loss",
        "Ipsilateral Diaphragm Elevation — Hemidiaphragm rises on affected side",
        "Compensatory Hyperinflation — Adjacent lobes appear overly lucent",
        "Juxtaphrenic Peak — Small triangular peak at diaphragm dome",
    ],
    "Pneumothorax": [
        "Visceral Pleural Line — Sharp white pleural edge separated by air",
        "Peripheral Hyperlucency — Area beyond the line lacks vascular markings",
        "Collapsed Lung Contour — Retracted dense lung centrally located",
        "Deep Sulcus Sign — Deepened costophrenic recess on supine film",
        "Mediastinal Shift Away — Contralateral deviation in tension pneumothorax",
        "Depressed Hemidiaphragm — Downward push on diaphragm by pleural pressure",
        "Air-Fluid Level — Horizontal interface in hydropneumothorax",
    ],
    "Pleural Effusion": [
        "Blunted Costophrenic Angle — Loss of acute recess at lung base",
        "Pleural Meniscus Sign — Curved upper margin of fluid against chest wall",
        "Fluid Tracking in Fissure — Lentiform opacity along an interlobar fissure",
        "Subpulmonic Effusion — Apparent diaphragm elevation from fluid beneath lung",
        "Gravity-Dependent Layering — Free fluid shifts on decubitus view",
        "Loculated Effusion — Fixed lenticular opacity with obtuse margins",
        "Massive Effusion with Shift — Opaque hemithorax and contralateral mediastinal displacement",
        "Hemidiaphragm Silhouette Loss — Fluid obscures diaphragm outline",
    ],
    "Infiltration": [
        "Patchy Air-Space Opacity — Fluffy alveolar densities blurring vessels",
        "Ground-Glass Opacity — Hazy density preserving bronchial margins",
        "Reticular Pattern — Network of intersecting linear opacities",
        "Kerley B Septal Lines — Short peripheral septal lines at bases",
        "Micronodular Pattern — Diffuse tiny nodules ≤3 mm",
        "Macronodular Pattern — Multiple nodules >3 mm",
        "Reticulonodular Pattern — Combined fine lines and small nodules",
        "Honeycombing — Stacked cystic airspaces in subpleural lung",
    ],
    "Mass": [
        "Large Rounded Opacity — Focal soft‑tissue density >3 cm",
        "Sharp Borders — Well‑defined margin separating mass from lung",
        "Lobulated Contour — Scalloped outer edge of the lesion",
        "Internal Cavitation — Central radiolucent area within mass",
        "Air-Fluid Level in Cavity — Horizontal gas–liquid interface inside",
        "Obtuse Chest Wall Angle — Edge meets pleura at obtuse angle, suggesting extrapulmonary origin",
        "Coarse Calcification — Dense calcific focus within mass",
    ],
    "Nodule": [
        "Small Rounded Opacity — Discrete lesion ≤3 cm in diameter",
        "Variable Margin — Edge may be smooth or irregular",
        "Homogeneous Density — Uniform soft‑tissue attenuation",
        "Cavitary Nodule — Central lucency inside the nodule",
        "Central Calcification — Dense focus suggesting healed granuloma",
        "Multiple Discrete Nodules — Several similar lesions scattered",
        "Micronodule Cluster — Numerous nodules <3 mm (miliary spread)",
        "Acinar Nodule — Poorly defined 5–8 mm opacity",
    ],
    "Emphysema": [
        "Hyperinflated Lung Volumes — ≥10 posterior ribs visible on PA film",
        "Flattened Diaphragms — Low, flattened dome shape of hemidiaphragms",
        "Barrel Chest — Increased antero‑posterior diameter on lateral view",
        "Increased Retrosternal Clear Space — Wider lucent zone anterior to mediastinum",
        "Hyperlucent Lung Fields — Darker lungs with sparse vascular markings",
        "Bullae — Thin‑walled airspaces ≥1 cm representing destroyed lung",
    ],
    "Fibrosis": [
        "Reticular Pattern — Fine/coarse intersecting lines from scar tissue",
        "Honeycombing Cysts — Stacked subpleural cystic airspaces",
        "Parenchymal Band — Linear opacity extending to pleura",
        "Architectural Distortion — Displacement of bronchi, vessels, or fissures",
        "Traction Bronchiectasis — Dilated airways within fibrotic zones",
        "Volume Loss — Shrinkage with diaphragm or fissure elevation",
        "Basal Subpleural Predominance — Lower peripheral distribution of changes",
        "Juxtaphrenic Peak Sign — Triangular diaphragm peak with upper‑lobe fibrosis",
    ],
    "Pleural Thickening": [
        "Pleural Plaque — Flat/nodular pleural opacity along ribs or diaphragm",
        "Calcified Plaque — Dense linear or nodular pleural calcification",
        "Diffuse Pleural Thickening — Broad smooth rind‑like pleural density",
        "Parenchymal Band — Linear pleuro‑parenchymal scar extending inward",
        "Rounded Atelectasis — Peripheral round mass with curving ‘comet‑tail’ vessels",
        "Subpleural Curvilinear Line — Thin horizontal line paralleling pleura",
    ],
    "Hernia": [
        "Retrocardiac Air-Fluid Level — Horizontal interface inside herniated stomach",
        "Retrocardiac Gas-Containing Mass — Oval gas pocket behind heart silhouette",
        "Intrathoracic Gastric Bubble — Stomach fundus seen above diaphragm",
    ],
}
